# Generated by Django 5.2 on 2025-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_messagerequest_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
