# Generated by Django 5.2 on 2025-04-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='BookingRequest',
        ),
    ]
